version: ${resolve_default:debug,${..version}}
gpu: ${resolve_default:0,${..gpu}}
env_name: fly_single_clip
algo_name: ppo
task_name: track
note: 
num_envs: 1024
num_timesteps: 3_000_000_000
eval_every: 10_000_000
episode_length: 250
batch_size: 1024
learning_rate: 3e-4
num_minibatches: 32
num_updates_per_batch: 16
clipping_epsilon: 0.3
entropy_cost: 1e-3
action_repeat: 1
unroll_length: 16
discounting: 0.99
mlp_policy_layer_sizes: [256, 256]
